# Generated by Django 5.1.1 on 2025-01-10 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carrito', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='estado',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='carrito',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to='carrito.carrito'),
        ),
    ]
